### ISSUE TITLE
proper way to configure istio for injecting

### ISSUE THREAD

**Issue by sokoow** [solo-io/supergloo#164]
Probably related to https://github.com/solo-io/supergloo/issues/83 . Installed istio in its own istio namespace, now trying to inject anything and got:

```
$ istioctl kube-inject -f ./httpbin.yaml 
Error: could not read valid configmap "istio" from namespace  "istio-system": configmaps "istio" not found - Use --meshConfigFile or re-run kube-inject with `-i <istioSystemNamespace> and ensure valid MeshConfig exists
```

**Comment by ilackarms** [comment]
is istio installed in the `istio-system` namespace? if not, you'll need to run the `istioctl kube-inject` command with the flag `--istioNamespace` set to the ns where istio was installed
