### ISSUE TITLE
Fix logos

### ISSUE THREAD

**Issue by dankohn** [solo-io/supergloo#309]
In your MultiMesh image in the Readme, the Azure, AWS, and Squash logos are all out of date and the Google Cloud one is squished.

**Comment by ilackarms** [comment]
good point! thanks for the heads up.
we'll make sure to track this and have it fixed soon

**Comment by dankohn** [comment]
You don't seem to have fixed this.

**Comment by rickducott** [comment]
Sorry @dankohn, that was a mistake.
