### ISSUE TITLE
Can't enable/disable ingress and egress (Istio)

### ISSUE THREAD

**Issue by peterj** [solo-io/supergloo#403]
The `gatewayInstallOptions` is never set in the `helmChartParams`, so by default when installing Istio, ingress/egress gateway does not get installed (not sure if this is by design or not).

**Comment by ilackarms** [comment]
@peterj it was installed for the first iterations of the installer, but turned off due to some issues it was causing. we do intend to bring it back, but have been focused on other stuff. 

is this a priority for you? it's a relatively simple change to make; in fact, a PR would be great if you think you could handle it with some guidance. 

definitely on our roadmap. for now i would recommend installing istio via the helm chart and running supergloo with `mesh-discovery`

**Comment by ilackarms** [comment]
*note* that for certificate rotation to work, if istio isn't a managed install, you will need to re-run the helm chart yourself with `--set security.selfSigned=true/false` (`false` when configuring a custom root ca with supergloo, `true` when removing the custom ca config and telling istio to sign its own certificate)

this is a known issue that we're also working to address

**Comment by peterj** [comment]
Not a high priority, I was just playing with it and noticed that it's defined, but not actually set anywhere. 

I can take a stab at it and create a PR. Seems like it's a matter of updating the install.proto to include the two options (ingress/egress), add the flags to the CLI and include the `gatewayInstallOptions` instance in the `helmChartParams` in `makeManifestsForInstall` (+ adding/updating unit tests).

**Comment by ilackarms** [comment]
yes! exactly. we hard coded a lot of defaults as we expect that part of the code to evolve significantly once we start dealing with supporting multiple istio versions (coming soon)

**Comment by peterj** [comment]
Perfect! I'll go through the developer.md to set up everything properly and then work on the PR.

**Comment by ilackarms** [comment]
if you require an ingress, you can install [gloo](https://supergloo.solo.io/mesh/gloo-istio-mtls/) to use as your istio ingress

however we absolutely intend to support istio's ingress! it will require some support on supergloo's api to configure ingress traffic

**Comment by ilackarms** [comment]
awesome! feel free to ping me here or on slack with any questions
