### ISSUE TITLE
brew install - No available formula with the name "supergloo"

### ISSUE THREAD

**Issue by ericgoode** [solo-io/supergloo#487]
brew install supergloo

Error: No available formula with the name "supergloo"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by scranton** [comment]
try brew install solo-io/tap/supergloo

Looks like install docs were recently broken...
