### ISSUE TITLE
Update CLI init to deploy to kubernetes

### ISSUE THREAD

**Issue by rickducott** [solo-io/supergloo#58]
Installation guide currently recommends deploying server locally before using the CLI. The CLI has an initialization hook that ensures Helm is set up and the supergloo-system namespace is created, but doesn't currently deploy the server pod to kubernetes.

**Comment by rickducott** [comment]
Need to make sure consul tunneling is working appropriately.

**Comment by ilevine** [comment]
https://github.com/solo-io/supergloo/pull/69

**Comment by rickducott** [comment]
Done
